### ISSUE TITLE
BCL UVMLint

### ISSUE THREAD

**Issue by ak-vworks** [accellera-official/uvm-core#11] opened 2024-04-26 10:21 UTC
Hi,
  As part of our development @AsFigo we developed a custom UVMLint for BCL and the results can be found at https://asfigo.blogspot.com/2024/03/customizing-uvmlint-for-ieee-18002-base.html 

Happy to share more details if anyone is interested.

Ajeetha
AsFigo

**Comment by mstrickland-mrvl** [comment] 2024-08-08 16:26
Thanks for providing these results.  We will close this as "not a bug".

**Closed by mstrickland-mrvl** 2024-08-08 16:26 UTC
Labels: not a bug

**Comment by jwayar** [comment] 2025-08-20 15:24
> Hi, As part of our development [@AsFigo](https://github.com/AsFigo) we developed a custom UVMLint for BCL and the results can be found at https://asfigo.blogspot.com/2024/03/customizing-uvmlint-for-ieee-18002-base.html
> 
> Happy to share more details if anyone is interested.
> 
> Ajeetha AsFigo

Hi! I'am interested, how to abtain more details?
